name: Preparant per producció
run-name: ${{ github.actor }} està pujant l'aplicació a PROD 🚀
on:
  push:
    branches:
      - main
jobs:
  Pujar-a-produccio-amb-SCP:
    runs-on: ubuntu-latest
    steps:
      - name: Obtenint el codi del respositori
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm install
        working-directory: ./web/vue-project  

      - name: Construir el proyecto Vue
        run: npm run build
        working-directory: ./web/vue-project  

      - name: scp a produccio
        run: |
          echo "${{ secrets.PROD_KEY }}" > ~/prod_key.pem
          chmod 600 ~/prod_key.pem
          cd ${{ github.workspace }}
          echo "Action desplegant a produccio" > ./web/last_deploy.txt
          date >> ./web/last_deploy.txt
          scp -r -o stricthostkeychecking=no -o UserKnownHostsFile=/dev/null -i "~/prod_key.pem" ./web/vue-project/dist/* ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}:/home/a16miqbargim/web/actions.a16miqbargim.daw.inspedralbes.cat/public_html/
          
      - run: echo "🍏 This job's status is ${{ job.status }}."
